heat_template_version: 2013-05-23

description: >
  Hello world HOT template that just defines a single server.
  Contains just base features to verify base HOT support.

parameters:
  key_name:
    type: string
    description: Name of an existing key pair to use for the server
    constraints:
      - custom_constraint: nova.keypair
  flavor:
    type: string
    description: Flavor utilisee par les serveurs
    default: INF4410-mini
  image:
    type: string
    description: Image utilisee pour les serveurs
    default: INF4410-Ubuntu-trusty-mini
  admin_pass:
    type: string
    description: Admin password
    hidden: true
    constraints:
      - length: { min: 6, max: 8 }
        description: Password length must be between 6 and 8 characters
      - allowed_pattern: "[a-zA-Z0-9]+"
        description: Password must consist of characters and numbers only
      - allowed_pattern: "[A-Z]+[a-zA-Z0-9]*"
        description: Password must start with an uppercase character
  net_id:
    type: string
    label: networks
    default: inf4410-net


resources:
  server:
    type: OS::Nova::Server
    properties:
      key_name: { get_param: key_name }
      image: { get_param: image }
      flavor: { get_param: flavor }
      admin_pass: { get_param: admin_pass }
      networks:
        - network: { get_param: net_id }
      user_data_format: RAW
      user_data:
        str_replace:
          template: |
            #!/bin/bash
            wget https://raw.githubusercontent.com/houssemmh/INF4410-TP3/master/server.py
            python server.py &
          params:
            param1: 'string'
            
outputs:
  server_networks:
    description: The networks of the deployed server
    value: { get_attr: [server, networks] }
