heat_template_version: 2014-10-16

description: A template to deploy a load balanced web server

parameters:
  image:
    type: string
    description: Image utilisee pour les serveurs
    default: INF4410-Ubuntu-trusty-mini

  flavor:
    type: string
    description: Flavor utilisee par les serveurs
    default: INF4410-mini

  subnet_id:
    type: string
    description: Sous-reseau dans lequel le load balancer sera situe
    default:  inf4410-net

resources:
   my_instance:
    type: OS::Nova::Server
    properties:
     admin_pass: root
     key_name: nicotheo
     flavor: {get_param: flavor}
     image: {get_param: image}
     networks:
      - network: {get_param: subnet_id}
     user_data:
      str_replace:
       template: |
        #!/bin/bash
        wget https://raw.githubusercontent.com/houssemmh/INF4410-TP3/master/server.py 
        python server.py &
       params : 
         $rootPassword: root

#   mypool:
#       type: OS::Neutron::Pool
#       #A completer

#   loadbalancer:
#       type: OS::Neutron::LoadBalancer
#       #A completer

#   monitor:
#       type: OS::Neutron::HealthMonitor
#       #properties:


# outputs:
#   pool_ip_address:
#     value: {get_attr: [mypool, vip, address]}
#     description: The IP address of the load balancing pool
